// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanPayer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanPayer.domain.Beneficiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Beneficiario");
                });

            modelBuilder.Entity("LoanPayer.domain.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("LoanPayer.domain.ClienteBeneficiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdBeneficiario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClienteBeneficiario");
                });

            modelBuilder.Entity("LoanPayer.domain.Comprador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContatoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("Comprador");
                });

            modelBuilder.Entity("LoanPayer.domain.ContaBancaria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClienteBeneficiario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTipoConta")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NumAgencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NumBanco")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NumConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Recebe")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ContaBancaria");
                });

            modelBuilder.Entity("LoanPayer.domain.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ddd")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("LoanPayer.domain.DetalheVenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CodBarras")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtVencimento")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdFormaPagamento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRecebimento")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<long>("IdVenda")
                        .HasColumnType("bigint");

                    b.Property<bool>("LiberaComissao")
                        .HasColumnType("bit");

                    b.Property<string>("NumCheque")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Parcela")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DetalheVenda");
                });

            modelBuilder.Entity("LoanPayer.domain.DetalheVendaClienteBenefic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comprovante")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClienteBeneficiario")
                        .HasColumnType("bigint");

                    b.Property<long>("IdDetalheVenda")
                        .HasColumnType("bigint");

                    b.Property<long>("IdStatusPagamento")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<bool>("LiberaComissao")
                        .HasColumnType("bit");

                    b.Property<decimal>("VlComissao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DetalheVendaClienteBenefic");
                });

            modelBuilder.Entity("LoanPayer.domain.Empreendimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Empreendimento");
                });

            modelBuilder.Entity("LoanPayer.domain.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("LoanPayer.domain.FormaPagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FormaPagamento");
                });

            modelBuilder.Entity("LoanPayer.domain.StatusPagamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StatusPagamento");
                });

            modelBuilder.Entity("LoanPayer.domain.TipoConta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TipoConta");
                });

            modelBuilder.Entity("LoanPayer.domain.Torre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdEmpreendimento")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeTorre")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Torre");
                });

            modelBuilder.Entity("LoanPayer.domain.Unidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTorre")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("LoanPayer.domain.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LoanPayer.domain.Venda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DtDelete")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtUpdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdComprador")
                        .HasColumnType("bigint");

                    b.Property<long>("IdStatusVenda")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUnidade")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserCreate")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserDelete")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdUserUpdate")
                        .HasColumnType("bigint");

                    b.Property<long>("NumContrato")
                        .HasColumnType("bigint")
                        .HasMaxLength(500);

                    b.Property<int>("QtdParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorComissaoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("LoanPayer.domain.Beneficiario", b =>
                {
                    b.HasOne("LoanPayer.domain.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanPayer.domain.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanPayer.domain.Cliente", b =>
                {
                    b.HasOne("LoanPayer.domain.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanPayer.domain.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanPayer.domain.Comprador", b =>
                {
                    b.HasOne("LoanPayer.domain.Contato", "Contato")
                        .WithMany()
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanPayer.domain.Empreendimento", b =>
                {
                    b.HasOne("LoanPayer.domain.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
